Obj_Tree = {
    'Simulation_Parameters': [
        'Version', 'Timestep', 'ConvergenceLimits', 'Building',
        'SurfaceConvectionAlgorithm:Inside', 'SurfaceConvectionAlgorithm:Outside',
        'HeatBalanceAlgorithm', 'HeatBalanceSettings:ConductionFiniteDifference',
        'ZoneAirHeatBalanceAlgorithm', 'ZoneAirContaminantBalance', 'ShadowCalculation',
        'Output:Diagnostics', 'Output:DebuggingData', 'Output:PreprocessorMessage',
        'ZoneCapacitanceMultiplier:ResearchSpecial', 'SimulationControl'
    ],
    'Location': [
        'Site:Location',
        'Site:VariableLocation',
        'SizingPeriod:DesignDay',
        'Longer Design Periods',
        'SizingPeriod:WeatherFileDays',
        'SizingPeriod:WeatherFileConditionType',
        'RunPeriod',
        'RunPeriodControl:SpecialDays',
        'RunPeriodControl:DaylightSavingTime',
        'WeatherProperty:SkyTemperature',
        'Site:WeatherStation',
        'Site:HeightVariation',
        'Site:GroundTemperature:BuildingSurface',
        'Site:GroundTemperature:Shallow',
        'Site:GroundTemperature:Deep',
        'Site:GroundTemperature:Undisturbed:FiniteDifference',
        'Site:GroundTemperature:Undisturbed:KusudaAchenbach',
        'Site:GroundTemperature:Undisturbed:Xing',
        'Site:GroundDomain:Slab',
        'Site:GroundDomain:Basement',
        'Site:GroundTemperature:FCfactorMethod',
        'Site:GroundReflectance',
        'Site:GroundReflectance:SnowModifier',
        'Site:WaterMainsTemperature',
        'Site:Precipitation',
    ],
    'Schedules': [
        'ScheduleTypeLimits',
        'Schedule:Day:Hourly',
        'Schedule:Day:Interval',
        'Schedule:Day:List',
        'Schedule:Week:Daily',
        'Schedule:Week:Compact',
        'Schedule:Year',
        'Schedule:Compact',
        'Schedule:Constant',
    ],
    'HVAC_Branch': [
        'NodeList',
        'BranchList',
        'Branch',
        'ConnectorList',
        'Connector:Splitter',
        'Connector:Mixer',
        'Pipe:Adiabatic',
        'Pipe:Adiabatic:Steam',
        'Pipe:Indoor',
        'Pipe:Outdoor',
        'Pipe:Underground',
        'PipingSystem:Underground:Domain',
        'PipingSystem:Underground:PipeCircuit',
        'PipingSystem:Underground:PipeSegment',
        'Duct',
    ],
    'PlantLoops': [
        'PlantLoop',
        'CondenserLoop'
    ],
    'Plant_Controls': [
        'PlantEquipmentOperationSchemes',
        'CondenserEquipmentOperationSchemes',
        'PlantEquipmentOperation:Uncontrolled',
        'PlantEquipmentOperation:CoolingLoad',
        'PlantEquipmentOperation:HeatingLoad',
        'PlantEquipmentOperation:OutdoorDryBulb',
        'PlantEquipmentOperation:OutdoorWetBulb',
        'PlantEquipmentOperation:OutdoorRelativeHumidity',
        'PlantEquipmentOperation:OutdoorDewpoint',
        'PlantEquipmentOperation:OutdoorDryBulbDifference',
        'PlantEquipmentOperation:OutdoorWetBulbDifference',
        'PlantEquipmentOperation:OutdoorDewpointDifference',
        'PlantEquipmentOperation:ComponentSetpoint',
        'PlantEquipmentOperation:ThermalEnergyStorage',
        'PlantEquipmentOperation:ChillerHeaterChangeover',
        'PlantEquipmentList',
        'CondenserEquipmentList',
    ],
    'Plant_Equipment': [
        'Chiller:Absorption',
        'Chiller:Absorption:Indirect',
        'Chiller:ConstantCOP',
        'Chiller:Electric',
        'Chiller:Electric:ASHRAE205',
        'Chiller:Electric:EIR',
        'Chiller:Electric:ReformulatedEIR',
        'Chiller:EngineDriven',
        'Chiller:CombustionTurbine',
        'ChillerHeater:Absorption:DirectFired',
        'ChillerHeater:Absorption:DoubleEffect',
        'Boiler:HotWater',
        'Boiler:Steam',
        'HeatPump:WaterToWater:EquationFit:Cooling',
        'HeatPump:WaterToWater:EquationFit:Heating',
        'HeatPump:WaterToWater:ParameterEstimation:Cooling',
        'HeatPump:WaterToWater:ParameterEstimation:Heating',
        'HeatPump:PlantLoop:EIR:Cooling',
        'HeatPump:PlantLoop:EIR:Heating',
        # 'HeatPump:AirToWater:FuelFired:Heating (and Cooling)',
        'DistrictCooling',
        'DistrictHeating:Water',
        'DistrictHeating:Steam',
        'PlantComponent:TemperatureSource',
        'CentralHeatPumpSystem',
        'ChillerHeaterPerformance:Electric:EIR',
    ],
    'Water_Heaters_and_Thermal_Storage': [
        'WaterHeater:Mixed',
        'WaterHeater:Stratified',
        'WaterHeater:Sizing',
        'WaterHeater:HeatPump:PumpedCondenser',
        'WaterHeater:HeatPump:WrappedCondenser',
        'ThermalStorage:Ice:Simple',
        'ThermalStorage:Ice:Detailed',
        'ThermalStorage:ChilledWater:Mixed',
        'ThermalStorage:ChilledWater:Stratified',
    ],
    'Water_Use': [
        'WaterUse:Equipment',
        'WaterUse:Connections',
        'WaterUse:Storage',
        'WaterUse:RainCollector',
        'WaterUse:Well',
    ],
    'Condenser_Equipment': [
        'CoolingTower:SingleSpeed',
        'CoolingTower:TwoSpeed',
        'CoolingTower:VariableSpeed:Merkel',
        'CoolingTower:VariableSpeed',
        'CoolingTowerPerformance:CoolTools',
        'CoolingTowerPerformance:YorkCalc',
        'EvaporativeFluidCooler:SingleSpeed',
        'EvaporativeFluidCooler:TwoSpeed',
        'FluidCooler:SingleSpeed',
        'FluidCooler:TwoSpeed',
        'GroundHeatExchanger:System',
        'GroundHeatExchanger:Vertical:Properties',
        'GroundHeatExchanger:Vertical:Array',
        'GroundHeatExchanger:Vertical:Single',
        'GroundHeatExchanger:ResponseFactors',
        'GroundHeatExchanger:Slinky',
        'GroundHeatExchanger:Pond',
        'GroundHeatExchanger:Surface',
        'GroundHeatExchanger:HorizontalTrench',
        'HeatExchanger:FluidToFluid',
    ],
    'Air_Distribution': [
        'AirLoopHVAC',
        'AirLoopHVAC:ControllerList',
        'AvailabilityManagerAssignmentList',
        'AirLoopHVAC:OutdoorAirSystem',
        'AirLoopHVAC:OutdoorAirSystem:EquipmentList',
        'OutdoorAir:Node',
        'OutdoorAir:NodeList',
        'OutdoorAir:Mixer',
    ],
    'Unitary': [
        'AirLoopHVAC:UnitarySystem',
        'AirLoopHVAC:Unitary:Furnace:HeatCool',
        'AirLoopHVAC:UnitaryHeatCool',
        'AirLoopHVAC:UnitaryHeatPump:AirToAir',
        'AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed',
        'AirLoopHVAC:Unitary:Furnace:HeatOnly',
        'AirLoopHVAC:UnitaryHeatOnly',
        'AirLoopHVAC:UnitaryHeatPump:WaterToAir',
        'AirLoopHVAC:UnitaryHeatCool:VAVChangeoverBypass',
    ],
    'Airflow_Network': [
        'AirflowNetwork:SimulationControl',
        'AirflowNetwork:MultiZone:Zone',
        'AirflowNetwork:MultiZone:Surface',
        'AirflowNetwork:MultiZone:ReferenceCrackConditions',
        'AirflowNetwork:MultiZone:Surface:Crack',
        'AirflowNetwork:MultiZone:Surface:EffectiveLeakageArea',
        'AirflowNetwork:MultiZone:SpecifiedFlowRate',
        'AirflowNetwork:MultiZone:Component:DetailedOpening',
        'AirflowNetwork:MultiZone:Component:HorizontalOpening',
        'AirflowNetwork:MultiZone:Component:SimpleOpening',
        'AirflowNetwork:MultiZone:Component:ZoneExhaustFan',
        'AirflowNetwork:MultiZone:ExternalNode',
        'AirflowNetwork:MultiZone:WindPressureCoefficientArray',
        'AirflowNetwork:MultiZone:WindPressureCoefficientValues',
        'AirflowNetwork:OccupantVentilationControl',
        'AirflowNetwork:ZoneControl:PressureController',
        'AirflowNetwork:IntraZone:Node',
        'AirflowNetwork:IntraZone:Linkage',
        'AirflowNetwork:Distribution:DuctViewFactors',
        'AirflowNetwork:Distribution:Node',
        'AirflowNetwork:Distribution:Component:Leak',
        'AirflowNetwork:Distribution:Component:LeakageRatio',
        'AirflowNetwork:Distribution:Component:Duct',
        'AirflowNetwork:Distribution:Component:Fan',
        'AirflowNetwork:Distribution:Component:Coil',
        'AirflowNetwork:Distribution:Component:HeatExchanger',
        'AirflowNetwork:Distribution:Component:TerminalUnit',
        'AirflowNetwork:Distribution:Component:ConstantPressureDrop',
        'AirflowNetwork:Distribution:Component:OutdoorAirFlow',
        'AirflowNetwork:Distribution:Component:ReliefAirFlow',
        'AirflowNetwork:Distribution:Linkage',
        'AirflowNetwork:Distribution:DuctSizing',
    ],
    'Zone_Equipment': [
        'ZoneHVAC:AirDistributionUnit',
        'ZoneHVAC:EquipmentConnections',
        'ZoneHVAC:EquipmentList',
        'SpaceHVAC:EquipmentConnections',
        'SpaceHVAC:ZoneEquipmentSplitter',
        'SpaceHVAC:ZoneEquipmentMixer',
    ],
    'Air_Terminals': [
        'AirTerminal:SingleDuct:ConstantVolume:Reheat',
        'AirTerminal:SingleDuct:ConstantVolume:NoReheat',
        'AirTerminal:SingleDuct:VAV:Reheat',
        'AirTerminal:SingleDuct:VAV:Reheat:VariableSpeedFan',
        'AirTerminal:SingleDuct:VAV:HeatAndCool:Reheat',
        'AirTerminal:SingleDuct:VAV:NoReheat',
        'AirTerminal:SingleDuct:VAV:HeatAndCool:NoReheat',
        'AirTerminal:SingleDuct:SeriesPIU:Reheat',
        'AirTerminal:SingleDuct:ParallelPIU:Reheat',
        'AirTerminal:SingleDuct:ConstantVolume:FourPipeInduction',
        'AirTerminal:SingleDuct:ConstantVolume:FourPipeBeam',
        'AirTerminal:SingleDuct:ConstantVolume:CooledBeam',
        'AirTerminal:SingleDuct:Mixer',
        'AirTerminal:DualDuct:ConstantVolume',
        'AirTerminal:DualDuct:VAV',
        'AirTerminal:DualDuct:VAV:OutdoorAir',
    ],
    'Air_Path': [
        'AirLoopHVAC:SupplyPath',
        'AirLoopHVAC:ReturnPath',
        'AirLoopHVAC:ReturnPlenum',
        'AirLoopHVAC:SupplyPlenum',
        'AirLoopHVAC:ExhaustSystem',
        'ZoneHVAC:ExhaustControl',
        'AirLoopHVAC:ZoneSplitter',
        'AirLoopHVAC:ZoneMixer',
        'AirLoopHVAC:DedicatedOutdoorAirSystem',
        'AirLoopHVAC:Mixer',
        'AirLoopHVAC:Splitter',
    ],
    'Zone_Units': [
        'ZoneHVAC:IdealLoadsAirSystem',
        'ZoneHVAC:FourPipeFanCoil',
        'ZoneHVAC:UnitVentilator',
        'ZoneHVAC:UnitHeater',
        'ZoneHVAC:EvaporativeCoolerUnit',
        'ZoneHVAC:OutdoorAirUnit',
        'ZoneHVAC:OutdoorAirUnit:EquipmentList',
        'ZoneHVAC:WindowAirConditioner',
        'ZoneHVAC:PackagedTerminalAirConditioner',
        'ZoneHVAC:PackagedTerminalHeatPump',
        'ZoneHVAC:RefrigerationChillerSet',
        'ZoneHVAC:WaterToAirHeatPump',
        'ZoneHVAC:Dehumidifier:DX',
        'ZoneHVAC:EnergyRecoveryVentilator',
        'ZoneHVAC:TerminalUnit:VariableRefrigerantFlow',
        'ZoneHVAC:HybridUnitaryHVAC',
    ],
    'VRF_Equipments': [
        'AirConditioner:VariableRefrigerantFlow',
        'AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl',
        'AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl:HR',
        'ZoneTerminalUnitList',
    ],
    'Radiative_Units': [
        'ZoneHVAC:Baseboard:RadiantConvective:Water',
        'ZoneHVAC:Baseboard:RadiantConvective:Steam',
        'ZoneHVAC:Baseboard:RadiantConvective:Electric',
        'ZoneHVAC:CoolingPanel:RadiantConvective:Water',
        'ZoneHVAC:Baseboard:Convective:Water',
        'ZoneHVAC:Baseboard:Convective:Electric',
        'ZoneHVAC:LowTemperatureRadiant:VariableFlow',
        'ZoneHVAC:LowTemperatureRadiant:VariableFlow:Design',
        'ZoneHVAC:LowTemperatureRadiant:ConstantFlow',
        'ZoneHVAC:LowTemperatureRadiant:ConstantFlow:Design',
        'ZoneHVAC:LowTemperatureRadiant:Electric',
        'ZoneHVAC:LowTemperatureRadiant:SurfaceGroup',
        'ZoneHVAC:HighTemperatureRadiant',
        'ZoneHVAC:VentilatedSlab',
        'ZoneHVAC:VentilatedSlab:SlabGroup',
    ],
    'Pumps': [
        'Pump:VariableSpeed',
        'Pump:ConstantSpeed',
        'Pump:VariableSpeed:Condensate',
        'HeaderedPumps:ConstantSpeed',
        'HeaderedPumps:VariableSpeed',
    ],
    'Coils': [
        'Coil:Cooling:Water',
        'Coil:Cooling:Water:DetailedGeometry',
        'CoilSystem:Cooling:Water:HeatExchangerAssisted',
        'CoilSystem:Cooling:Water',
        'Coil:Heating:Water',
        'Coil:Heating:Steam',
        'Coil:Heating:Electric',
        'Coil:Heating:Electric:MultiStage',
        'Coil:Heating:Desuperheater',
        'Coil:Cooling:DX:VariableRefrigerantFlow',
        'Coil:Heating:DX:VariableRefrigerantFlow',
        'Coil:Cooling:DX:VariableRefrigerantFlow:FluidTemperatureControl',
        'Coil:Heating:DX:VariableRefrigerantFlow:FluidTemperatureControl',
        'Coil:Heating:Fuel',
        'Coil:Heating:Gas:MultiStage',
        'Coil:Cooling:DX:SingleSpeed',
        'Coil:Cooling:DX:TwoSpeed',
        'Coil:Cooling:DX:TwoStageWithHumidityControlMode',
        'Coil:Cooling:DX:MultiSpeed',
        'Coil:Cooling:DX:VariableSpeed',
        'CoilPerformance:DX:Cooling',
        'Coil:Heating:DX:SingleSpeed',
        'Coil:Heating:DX:MultiSpeed',
        'Coil:Heating:DX:VariableSpeed',
        'Coil:WaterHeating:Desuperheater',
        'CoilSystem:Cooling:DX',
        'CoilSystem:Heating:DX',
        'CoilSystem:Cooling:DX:HeatExchangerAssisted',
        'CoilSystem:IntegratedHeatPump:AirSource',
        'Coil:WaterHeating:AirToWaterHeatPump:Pumped',
        'Coil:WaterHeating:AirToWaterHeatPump:Wrapped',
        'Coil:WaterHeating:AirToWaterHeatPump:VariableSpeed',
        'Coil:Cooling:WaterToAirHeatPump:ParameterEstimation',
        'Coil:Cooling:WaterToAirHeatPump:EquationFit',
        'Coil:Cooling:WaterToAirHeatPump:VariableSpeedEquationFit',
        'Coil:Heating:WaterToAirHeatPump:ParameterEstimation',
        'Coil:Heating:WaterToAirHeatPump:EquationFit',
        'Coil:Heating:WaterToAirHeatPump:VariableSpeedEquationFit',
        'Coil:Cooling:DX:SingleSpeed:ThermalStorage',
        'Coil:Cooling:DX',
        'Coil:Cooling:DX:CurveFit:Performance',
        'Coil:Cooling:DX:CurveFit:OperatingMode',
        'Coil:Cooling:DX:CurveFit:Speed',
    ],
    'Fans': [
        'Fan:SystemModel',
        'Fan:ConstantVolume',
        'Fan:OnOff',
        'Fan:VariableVolume',
        'Fan:ZoneExhaust',
        'FanPerformance:NightVentilation',
        'Fan:ComponentModel',
    ],
    'Humidifiers_Dehumidifiers': [
        'Humidifier:Steam:Electric',
        'Humidifier:Steam:Gas',
        'Dehumidifier:Desiccant:NoFans',
        'Dehumidifier:Desiccant:System',
    ],
    'Availability_Managers': [
        'AvailabilityManager:Scheduled',
        'AvailabilityManager:ScheduledOn',
        'AvailabilityManager:ScheduledOff',
        'AvailabilityManager:NightCycle',
        'AvailabilityManager:DifferentialThermostat',
        'AvailabilityManager:HighTemperatureTurnOff',
        'AvailabilityManager:HighTemperatureTurnOn',
        'AvailabilityManager:LowTemperatureTurnOff',
        'AvailabilityManager:LowTemperatureTurnOn',
        'AvailabilityManager:NightVentilation',
        'AvailabilityManager:HybridVentilation',
        'AvailabilityManager:OptimumStart',
    ],
    'Setpoint_Managers': [
        'SetpointManager:Scheduled',
        'SetpointManager:Scheduled:DualSetpoint',
        'SetpointManager:OutdoorAirReset',
        'SetpointManager:SingleZone:Reheat',
        'SetpointManager:SingleZone:Heating',
        'SetpointManager:SingleZone:Cooling',
        'SetpointManager:SingleZone:Humidity:Minimum',
        'SetpointManager:SingleZone:Humidity:Maximum',
        'SetpointManager:MixedAir',
        'SetpointManager:OutdoorAirPretreat',
        'SetpointManager:Warmest',
        'SetpointManager:Coldest',
        'SetpointManager:ReturnAirBypassFlow',
        'SetpointManager:WarmestTemperatureFlow',
        'SetpointManager:MultiZone:Cooling:Average',
        'SetpointManager:MultiZone:Heating:Average',
        'SetpointManager:MultiZone:MinimumHumidity:Average',
        'SetpointManager:MultiZone:MaximumHumidity:Average',
        'SetpointManager:MultiZone:Humidity:Minimum',
        'SetpointManager:MultiZone:Humidity:Maximum',
        'SetpointManager:FollowOutdoorAirTemperature',
        'SetpointManager:FollowSystemNodeTemperature',
        'SetpointManager:FollowGroundTemperature',
        'SetpointManager:CondenserEnteringReset',
        'SetpointManager:CondenserEnteringReset:Ideal',
        'SetpointManager:SingleZone:OneStageCooling',
        'SetpointManager:SingleZone:OneStageHeating',
        'SetpointManager:ReturnTemperature:ChilledWater',
        'SetpointManager:ReturnTemperature:HotWater',
        'SetpointManager:SystemNodeReset:Temperature',
        'SetpointManager:SystemNodeReset:Humidity',
    ],
    'Controllers': [
        'Controller:WaterCoil',
        'Controller:OutdoorAir',
        # 'Controller:MechanicalVentilation',
        'ZoneHVAC:EnergyRecoveryVentilator:Controller',
    ],
    'Heat_Recovery': [
        'HeatExchanger:AirToAir:FlatPlate',
        'HeatExchanger:AirToAir:SensibleAndLatent',
        'HeatExchanger:Desiccant:BalancedFlow',
        'HeatExchanger:Desiccant:BalancedFlow:PerformanceDataType1',
    ],
    'Refrigeration': [
        'Refrigeration:CompressorRack',
        'Refrigeration:Case',
        'Refrigeration:CaseAndWalkInList',
        'Refrigeration:WalkIn',
        'Refrigeration Case and WalkIn Outputs',
        'Refrigeration:System',
        'Refrigeration:TranscriticalSystem',
        'Refrigeration:Compressor',
        'Refrigeration:CompressorList',
        'Refrigeration:Subcooler',
        'Refrigeration:Condenser:AirCooled',
        'Refrigeration:Condenser:EvaporativeCooled',
        'Refrigeration:Condenser:WaterCooled',
        'Refrigeration:Condenser:Cascade',
        'Refrigeration:GasCooler:AirCooled',
        'Refrigeration:TransferLoadList',
        'Refrigeration:SecondarySystem',
        'Refrigeration:AirChiller',
    ],
    'ElectricLoadCenterGenerator': [
        'ElectricLoadCenter:Transformer',
        'ElectricLoadCenter:Distribution',
        'ElectricLoadCenter:Generators',
        'ElectricLoadCenter:Inverter:Simple',
        'ElectricLoadCenter:Inverter:FunctionOfPower',
        'ElectricLoadCenter:Inverter:LookUpTable',
        'ElectricLoadCenter:Inverter:PVWatts',
        'ElectricLoadCenter:Storage:Converter',
        'ElectricLoadCenter:Storage:Simple',
        'ElectricLoadCenter:Storage:Battery',
        'ElectricLoadCenter:Storage:LiIonNMCBattery',
        'Generator:InternalCombustionEngine',
        'Generator:CombustionTurbine',
        'Generator:MicroTurbine',
        'Generator:MicroCHP',
        'Generator:MicroCHP:NonNormalizedParameters',
        'Generator:FuelCell',
        'Generator:FuelCell:PowerModule',
        'Generator:FuelCell:StackCooler',
        'Generator:FuelCell:AirSupply',
        'Generator:FuelCell:WaterSupply',
        'Generator:FuelCell:AuxiliaryHeater',
        'Generator:FuelCell:ExhaustGasToWaterHeatExchanger',
        'Generator:FuelCell:ElectricalStorage',
        'Generator:FuelCell:Inverter',
        'Generator:FuelSupply',
        'Generator:Photovoltaic',
        'PhotovoltaicPerformance:Simple',
        'PhotovoltaicPerformance:EquivalentOne-Diode',
        'PhotovoltaicPerformance:Sandia',
        'Generator:PVWatts',
        'Generator:WindTurbine',
    ],
    'Performance_Curves': [
        'Curve:Linear',
        'Curve:QuadLinear',
        'Curve:QuintLinear',
        'Curve:Quadratic',
        'Curve:Cubic',
        'Curve:Quartic',
        'Curve:Exponent',
        'Curve:Bicubic',
        'Curve:Biquadratic',
        'Curve:CubicLinear',
        'Curve:ChillerPartLoadWithLift',
        'Curve:QuadraticLinear',
        'Curve:Triquadratic',
        'Curve:Functional:PressureDrop',
        'Curve:FanPressureRise',
        'Curve:ExponentialSkewNormal',
        'Curve:Sigmoid',
        'Curve:RectangularHyperbola1',
        'Curve:RectangularHyperbola2',
        'Curve:ExponentialDecay',
        'Curve:DoubleExponentialDecay',
    ],
    'Performance_Tables': [
        'Table:Lookup',
        'Table:IndependentVariableList',
        'Table:IndependentVariable',
    ],
    'Design_Objects': [
        'DesignSpecification:OutdoorAir',
        'DesignSpecification:OutdoorAir:SpaceList',
        'DesignSpecification:ZoneAirDistribution',
        'Sizing:Parameters',
        'OutputControl:Sizing:Style',
        'Sizing:Zone',
        'DesignSpecification:ZoneHVAC:Sizing',
        'DesignSpecification:AirTerminal:Sizing',
    ],
    'System_Sizing': [
        'Sizing:System',
        'Sizing:Plant',
    ],
    'Outputs': [
        # Inputs for Outputs:
        'Output:VariableDictionary',
        'Output:Surfaces:List',
        'Output:Surfaces:Drawing',
        'Output:Schedules',
        'Output:Constructions',
        'Output:DaylightFactors',
        'Output:EnergyManagementSystem',
        'OutputControl:SurfaceColorScheme',
        'OutputControl:ReportingTolerances',
        'Output:Variable',
        'Output:Meter,'
        'Output:Meter:MeterFileOnly',
        'Output:Meter:Cumulative,'
        'Output:Meter:Cumulative:MeterFileOnly',
        'Output:EnvironmentalImpactFactors',
        'EnvironmentalImpactFactors',
        'FuelFactors',
        'Output:JSON',
        # 'Output:SQLite',
        'OutputControl:Files',

        # Outputs:
        # 'Output:Table:Monthly',
        # 'Output:Table:Annual',
        # 'Output:Table:ReportPeriod',
        # 'Output:Table:SummaryReports',
        # 'OutputControl:Table:Style',
    ],
    'EMS': [
        'EnergyManagementSystem:Program',
        'EnergyManagementSystem:ProgramCallingManager',
        'EnergyManagementSystem:Subroutine',
        'EnergyManagementSystem:TrendVariable',
        'EnergyManagementSystem:InternalVariable',
        'EnergyManagementSystem:GlobalVariable',
        'EnergyManagementSystem:Sensor',
        'EnergyManagementSystem:Actuator',
        'EnergyManagementSystem:OutputVariable',
        'EnergyManagementSystem:MeteredOutputVariable',
        'EnergyManagementSystem:CurveOrTableIndexVariable',
        'EnergyManagementSystem:ConstructionIndexVariable',
     ],
    'Geometry': [
        'FenestrationSurface:Detailed',
    ]
}
